#pragma once

enum R4300iExceptionType {
	EXC_INTERRUPT,
	EXC_TLB_MODIFICATION,
	EXC_TLB_MISS_R,
	EXC_TLB_MISS_W,
	EXC_ADDRESS_ERROR_R,
	EXC_ADDRESS_ERROR_W,
	EXC_BUS_ERROR_F,
	EXC_BUS_ERROR_LS,
	EXC_SYSCALL,
	EXC_BREAKPOINT,
	EXC_RESERVED_INSTRUCTION,
	EXC_COPROCESSOR_UNUSABLE,
	EXC_ARITHMETIC_OVERFLOW,
	EXC_TRAP,
	EXC_14,
	EXC_FLOATING_POINT,
	EXC_16,
	EXC_17,
	EXC_18,
	EXC_19,
	EXC_20,
	EXC_21,
	EXC_22,
	EXC_WATCH,
	EXC_24,
	EXC_25,
	EXC_26,
	EXC_27,
	EXC_28,
	EXC_29,
	EXC_30,
	EXC_31
};

enum R4300iFpuExceptionBit {
	FPU_EXC_BIT_INEXACT_OPERATION,
	FPU_EXC_BIT_UNDERFLOW,
	FPU_EXC_BIT_OVERFLOW,
	FPU_EXC_BIT_DIVISION_BY_ZERO,
	FPU_EXC_BIT_INVALID_OPERATION,
	FPU_EXC_BIT_UNIMPLEMENTED_OPERATION
};

struct R4300iException {
	R4300iExceptionType exception;
	R4300iFpuExceptionBit fpuExceptionBit;
};
